spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    username: root
    password: astro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    org:
     springframework:
      security: debug
       
    
 
my:
 secret:
  jwt: password